name: collection_ext
description: A set of useful extension methods for Dart collections, designed in the purpose of making it easier to write functional-programming-style, concise Dart code.

version: 0.2.0-dev
homepage: https://github.com/xinthink/dart_collection_ext/
repository: https://github.com/xinthink/dart_collection_ext/

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  tuple: ^1.0.3

dev_dependencies:
  test: ^1.9.4
  pedantic: ^1.8.0
